name: flutter_media_metadata
description: A Flutter plugin to read metadata of media files.
version: 1.0.0
homepage: https://github.com/alexmercerind/flutter_media_metadata
repository: https://github.com/alexmercerind/flutter_media_metadata
documentation: https://github.com/alexmercerind/flutter_media_metadata/blob/master/README.md

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.4
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.alexmercerind.flutter_media_metadata
        pluginClass: FlutterMediaMetadataPlugin
      windows:
        pluginClass: FlutterMediaMetadataPlugin
      linux:
        pluginClass: FlutterMediaMetadataPlugin
      ios:
        pluginClass: FlutterMediaMetadataPlugin
      macos:
        pluginClass: FlutterMediaMetadataPlugin
      web:
        pluginClass: MetadataRetriever
        fileName: src/flutter_media_metadata_web.dart
